FROM ubuntu:20.04

ADD workloadMongo2-4.py .
RUN apt-get update && \
    apt-get install -y python2.7 curl

RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
RUN python2.7 get-pip.py

RUN pip install pymongo==2.5.2
