reproduction:
  schedule: "/vagrant/schedules/tracing_tests/redis/schedules/redis_prod_tracer.yaml"
  result_folder: "/vagrant/tests/bugdetection/redis/"
  trace_location: "/tmp/history.txt"
  buggy_trace: /vagrant/schedules/tracing_tests/redis/traces/history_prod.txt
  cleanup: /vagrant/schedules/tracing_tests/redis/scripts/cleanup.sh
